name: Create new gifs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Run
      run: python3 make_gifs.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update docs" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
